name: Generate JSDoc
description: Checks the JSDoc comments for errors

runs:
  using: 'composite'
  steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Env
        run: |
          npm install -g documentation
          touch lintOut.txt
        shell: bash

      - name: Lint JSDoc Comments
        run: |
          documentation lint ./**/*.{js,ts} > lintOut.txt
        shell: bash

      - name: Check if lintOut.txt is empty
        run: |
          if [ -s lintOut.txt ]; then # check if not empty
            exit 1
          fi
        shell: bash
      # have an eye on https://github.com/actions/runner/issues/662 to avoid the if statements
      - if: failure()
        uses: mshick/add-pr-comment@v2
        with:
          message-path: lintOut.txt

      - if: failure()
        run: exit 1
        shell: bash
