name: Generate JSDoc
description: Generates markdown files from JSDoc comments and uploads them to the repo's wiki

inputs:
  secret:
    description: "Repo access token"
    required: true

runs:
  using: 'composite'
  steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Env
        run: |
          sudo apt update
          sudo apt install moreutils -y
          npm install -g jsdoc jsdoc-to-markdown
          mkdir documentation
        shell: bash

      - name: Build Documentation Files
        run: |
          for file in $(find . -name "*.js")
          do
            jsdoc2md "${file}" | sponge documentation/${file}.md
          done
        shell: bash

      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "documentation"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ inputs.secret }}