name: Generate JSDoc
description: Generates markdown files from JSDoc comments and uploads them to the repo's wiki

runs:
  using: 'composite'
  steps:
      - name: Gathering Files
        uses: tj-actions/glob@v17
        id: glob
        with:
          files: |
            **/*.[jt]s
            **/*.[jt]sx
            !**/.*
            !**/*.test.*
            !**/*.spec.*
            !**/*.config.*

      - name: Setup Env
        run: |
          npm i --save-dev typescript jsdoc-babel @babel/cli @babel/core@7.23.2 @babel/preset-env@7.23.2 @babel/preset-typescript@7.23.2 @babel/plugin-transform-class-properties @babel/plugin-transform-object-rest-spread
          npm i -g jsdoc-to-markdown
          mkdir -p wiki
        shell: bash

      - name: Check for config
        run: |
          if [ ! -e jsdoc2md.json ]
          then
            cp $GITHUB_ACTION_PATH/jsdoc2md.json ./
          fi
        shell: bash

      - name: Build Documentation Files
        run: |
          for file in ${{ steps.glob.outputs.paths }}
          do
            directory=$(dirname "${file}")
            filename=$(basename "${file}")
            extension="${filename##*.}"
            if [ "$extension" == js* ]; then
              output=$(jsdoc2md "${file}")
            else
              output=$(jsdoc2md "$file" --configure ./jsdoc2md.json)
            fi

            if [ ! -z "${output}" ]; then
              mkdir -p "wiki/${directory}"
              echo "${output}" > wiki/${file}.md
              echo "${file} processed"
            fi
          done
        shell: bash

      - name: Upload Documentation to Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          strategy: clone
