name: Generate JSDoc
description: Generates markdown files from JSDoc comments and uploads them to the repo's wiki

inputs:
  secret:
    description: "Repo access token"
    required: true

runs:
  using: 'composite'
  steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Env
        run: |
          npm install --save-dev typescript jsdoc-babel @babel/cli @babel/core @babel/preset-env @babel/preset-typescript jsdoc-to-markdown @babel/plugin-proposal-class-properties @babel/plugin-proposal-object-rest-spread
          mkdir documentation
          npm i -g jsdoc-to-markdown
        shell: bash

      - name: Check for config
        run: |
          if [ ! -e jsdoc2md.json ]
          then
            cp $GITHUB_ACTION_PATH/jsdoc2md.json ./
          fi
        shell: bash

      - name: Glob match
        uses: tj-actions/glob@v17
        id: glob
        with:
          files: |
            **/*.js
            **/*.jsx
            **/*.ts
            **/*.tsx
            !**/*.test.*
            !**/*.spec.*
            !node_modules

      - name: Build Documentation Files
        run: |
          shopt -s globstar
          shopt -s extglob
          for file in ${{ steps.glob.outputs.paths }}
          do
            echo "$file"
            filename=$(basename "${file}")
            if [ "$filename" != *.spec.* ] && [ "$filename" != *.test.* ]; then
              extension="${filename##*.}"
              if [ "$extension" == js* ]; then
                output=$(jsdoc2md "${file}")
              else
                output=$(jsdoc2md "$file" --configure ./jsdoc2md.json)
              fi
            fi

            if [ ! -z "${output}" ]; then
              touch documentation/${filename}.md
              echo "${output}" > documentation/${filename}.md
              echo "${file} processed"
            fi
          done
        shell: bash

      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "documentation"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ inputs.secret }}
